#!/bin/bash

my_exit() {
    echo "Usage: $0 command [sub-command]"
    echo "command:"
    echo "  serve path: Build and Start dev server for that path (e.g. serve basic)"
    echo "  clean: Remove derectories generated by build process."
    echo "  help: Print this."
    exit 1
}

if [ "$#" -eq 0 ]; then
    my_exit 1
fi

wasm_dirs=(
    pkg
    target
)

if [ "$1" = "serve" ]; then
    if [ "$#" -ne 2 ]; then
        my_exit 1
    fi

    dir=$2
    if [ -d "$dir" ] && [ -e "$dir/package.json" ]; then
        pushd .
        cd $dir
        npm install
        npm run build
        npm start
        popd
    fi
elif [ "$1" = "clean" ]; then
    if [ "$#" -ne 1 ]; then
        my_exit 1
    fi

    # Make npm clean itself
    for dir in *; do
        if [ -d "$dir" ] && [ -e "$dir/package.json" ]; then
            echo "=== Cleaning $dir... ==="
            pushd .
            cd $dir
            npm run clean-all
            # Make sure to remove wasm build results
            for wasm_dir in "${wasm_dirs[@]}"; do
                rm -rf $wasm_dir
            done
            popd
        fi
    done
    echo "=== Done. ==="
else
    my_exit 1
fi
