[package]
name = "basic"
description = "wgpu + webpack base"
repository = "https://github.com/ecoricemon/webgpu-tutorial"
license = "Apache-2.0, MIT"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true

[dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
wgpu = "0.16.2"
web-sys = { version = "0.3.64", features = [
    "Window",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "MouseEvent"
]}
winit = "0.28.6"
bytemuck = { version = "1.13.1", features = [
    "derive",
    "min_const_generics"
]}
paste = "1.0.14"
cgmath = "0.18"
js-sys = "0.3.64"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = "0.4.19"

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.3.37"
